### PR TITLE
vfio: ci: don't clone with --depth=1

### LINKED ISSUE #3052: ci: vfio:  fatal: reference is not a tree: b7f6d3e0679796e907ecca88cfab0e32e326850d
VFIO is failing

```
15:14:51 + sriov_plugin_version=b7f6d3e0679796e907ecca88cfab0e32e326850d
15:14:51 + git clone --depth=1 https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin
15:14:51 Cloning into 'sriov-network-device-plugin'...
15:14:53 /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/tests/sriov-network-device-plugin /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/tests
15:14:53 + pushd sriov-network-device-plugin
15:14:53 + git checkout b7f6d3e0679796e907ecca88cfab0e32e326850d
15:14:53 fatal: reference is not a tree: b7f6d3e0679796e907ecca88cfab0e32e326850d
15:14:53 Failed at 161: git checkout "${sriov_plugin_version}"
15:14:53 ++ handle_error 161
15:14:53 ++ local exit_code=128
15:14:53 ++ local line_number=161
15:14:53 ++ echo 'Failed at 161: git checkout "${sriov_plugin_version}"'
15:14:53 ++ exit 128
15:14:53 + cleanup
```

### PR DESCRIPTION
**Pull request by devimc**
Don't clone k8snetworkplumbingwg/sriov-network-device-plugin using
--depth=1, otherwise `git clone` will fail if the commit version
tagged in the versions.yaml is not the latest commit in that repo.

fixes #3052

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by jcvenegas — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

File: integration/kubernetes/vfio.sh [hunk 1]
```diff
@@ -156,7 +156,7 @@ main() {
 	# Install network (device) plugin
 	sriov_plugin_url=$(get_version "plugins.sriov-network-device.url")
 	sriov_plugin_version=$(get_version "plugins.sriov-network-device.version")
-	git clone --depth=1 "${sriov_plugin_url}"
+	git clone "${sriov_plugin_url}"
```
Comment (jodh-intel) [inline integration/kubernetes/vfio.sh:159]: Testing shows that `--depth=4` is sufficient here ;)

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc!
