### PR TITLE
ci: fix VFIO CI

### LINKED ISSUE #3013: ci: fix VFIO CI
vfio POD must be deleted after checking the net interfaces otherwise the following POD won't be created because there is POD already running with the same name and yaml.

### PR DESCRIPTION
**Pull request by devimc**
Delete vfio POD after checking the net interfaces otherwise the following PODs
won't be created since there is already a POD with the same name and yaml.
Due to bug #3013 I was unable to detect that VFIO hotplug is not working with
QEMU+initrd. Let's skip these tests until we get a fix.

fixes #3013

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

File: integration/kubernetes/vfio.sh [hunk 1]
```diff
@@ -127,6 +127,8 @@ run_test() {
 	else
 		info "Success: found 2 network interfaces"
 	fi
+
+	sudo -E kubectl delete pod "${pod_name}"
```
Comment (c3d) [inline integration/kubernetes/vfio.sh:131]: For symmetry, wouldn't it be nicer with a

```
kubectl delete -f "${SCRIPT_DIR}/runtimeclass_workloads/vfio.yaml"
```

?

Assuming maybe some day the manifest may need to add other resources.

File: .ci/configure_containerd_for_kata.sh [hunk 2]
```diff
@@ -15,6 +15,8 @@ readonly runc_path=$(command -v runc)
 sudo mkdir -p /etc/containerd/
 
 cat << EOT | sudo tee /etc/containerd/config.toml
+[debug]
+  level = "debug"
```
Comment (c3d) [inline .ci/configure_containerd_for_kata.sh:19]: This looks like a separate PR to me. It's unclear how this is related to the problem described in the PR title.

**Review by c3d — APPROVED** [review]
lgtm but with minor suggestions

File: .ci/configure_containerd_for_kata.sh (hunk 2 above)
Comment (devimc) [reply .ci/configure_containerd_for_kata.sh:19]: yeah - I agree, adding DNM and WIP label

**Review by likebreath — APPROVED** [review]
@devimc Great. Thanks for locating and fixing the issue. I wonder how it was passing before this fix..

**Review by GabyCT — APPROVED** [review]
