### PR TITLE
tests: Add test to verify that host networking fails

### LINKED ISSUE #528: Create test to check we error out when host networking is requested.
Once https://github.com/kata-containers/runtime/pull/507 is merged, add docker test to verify this behaviour.
```
$ sudo docker run -it --runtime=kata-runtime --net=host debian sh
docker: Error response from daemon: OCI runtime create failed: Host networking requested, not supported by kata-runtime: unknown.
```

### PR DESCRIPTION
**Pull request by GabyCT**
Add a docker integration tests that verifies than when a host
networking is requested the runtime fails.

Fixes #528

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
CI is not happy

```
ERROR: Got 1 errors, quitting
Makefile:62: recipe for target 'docker-stability' failed
make: *** [docker-stability] Error 1
```

**Comment by devimc** [comment]
seems like those errors are not related to this change, restarting jobs

**Comment by chavafg** [comment]
Seems that the issue is that when running this new test, kata is not deleting the record of the container in the `/var/lib/vc/sbs` directory, and then when `docker-stability` test runs, it fails because that container directory still exists.
@GabyCT Can you run this test on a local machine and check if something is left in `/var/lib/vc/sbs`

**Comment by GabyCT** [comment]
@chavafg thanks, I modified the test

**Comment by devimc** [comment]
> Seems that the issue is that when running this new test, kata is not deleting the record of the container in the /var/lib/vc/sbs directory, and then when docker-stability test runs, it fails because that container directory still exists.

@chavafg is there an issue filed for that bug ?

File: integration/docker/run_test.go [hunk 1]
```diff
@@ -233,3 +234,37 @@ var _ = Describe("Check read-only cgroup filesystem", func() {
...
+			_, stderr, exitCode = dockerRun(args...)
+			Expect(exitCode).NotTo(Equal(0))
+			Expect(stderr).NotTo(BeEmpty())
+			stdout, _, _ := dockerInspect("--format={{.Id}}", id)
+			Expect(stdout).NotTo(BeEmpty())
+			fileName := strings.TrimSpace(stdout)
+			filePath := "/var/lib/vc/sbs"
+			args := []string{filePath, fileName}
+			completeName := strings.Join(args, "/")
+			os.Remove(completeName)
```
Comment (devimc) [inline integration/docker/run_test.go]: os.Remove(filepath.Join(filePath, fileName))

**Comment by chavafg** [comment]
@devimc I don't think there is a bug opened, @GabyCT can you open an issue about it. We should not delete the `/var/lib/vc/sbs` in the test as it is a bug. Maybe we can keep it as a workaround until the issue gets fixed, or skip the test meanwhile.

**Comment by GabyCT** [comment]
@chavafg changes applied

**Comment by chavafg** [comment]
lgtm

**Comment by devimc** [comment]
restarting ubuntu-16-04 CI

**Comment by grahamwhaley** [comment]
this is all green - merging...
