### PR TITLE
test: Check OCI calls

### LINKED ISSUE #941: Create a test that asserts OCI calls
Docker 18.09 has broken the expected runtime behaviour (see https://github.com/kata-containers/runtime/issues/926).

To make it simpler and safer for us to update [the version of Docker we test with](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L154), we could create a new test that does the following:

- Clear the journald journal logs.
- Enable full debug.
- Create a container.
- Extract the debug logs for the runtime from the journal:
  ```
  $ sudo journalctl -q -o cat -a -t kata-runtime > ./runtime.log
  ```
- Extract lines matching `arguments=`:
  ```
  $ grep -o "arguments=[^ ]*" runtime.log --color|cut -d= -f2-|tr -d '"'|tr -d "\\\\"
  create
  state
  start
  state
  kill
  state
  kill
  delete
  ```

As shown, that will list all the runtime CLI calls as defined by the [OCI runtime lifecycle](https://github.com/opencontainers/runtime-spec/blob/master/runtime.md).

We can then validate that list of calls against what we expect. For reference see the following, which shows the incorrect calls from containerd:

- https://github.com/moby/moby/issues/38233#issuecomment-440687251
- https://github.com/moby/moby/issues/38233#issuecomment-440725686

### PR DESCRIPTION
**Pull request by GabyCT**
Check OCI calls while running a docker run, docker stop and
docker run ..true in order to compare the arguments that we get
while running the containers with the OCI calls.

Fixes #941

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: integration/oci_calls/oci_call_test.sh [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+
+	get_debug_logs
+
+	check_arguments
+
+	docker rm -f ${NAME} > /dev/null
+}
+
+function run_oci_call_true() {
+	declare -a oci_call=( "create" "start" "state" "kill" "delete" )
```
[the remark this answers is not in the document]
Comment (sboeuf) [reply integration/oci_calls/oci_call_test.sh]: Might be worth putting a comment here, saying that this will soon change with the latest version of Docker 18.09 which relies on containerd 1.2.0. This behavioral change has been introduced by containerd.

and you can anticipate by having a commented out line like this:
```bash
function run_oci_call_true() {
        #declare -a oci_call=( "create" "start" "state" "delete" )
	declare -a oci_call=( "create" "start" "state" "kill" "delete" )
```

**Comment by GabyCT** [comment]
@sboeuf changes applied, thanks :)

**Comment by sboeuf** [comment]
thanks @GabyCT

File: integration/oci_calls/oci_call_test.sh [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+
+	check_arguments
+
+	docker rm -f ${NAME} > /dev/null
+}
+
+function run_oci_call_true() {
+	# Find docker version
+	version=$(docker version --format '{{.Server.Version}}' | cut -d '.' -f1-2)
+	echo "$version>=18.06" | bc
```
Comment (jodh-intel) [inline integration/oci_calls/oci_call_test.sh]: This is neat, but actually incorrect because the value you need to check on is not `$?` - it's the number that `bc` returns. So something like:

```
result=$(echo "$version>=18.06" | bc)
if [ $result -ne 1 ]; then
    ...
```

**Comment by GabyCT** [comment]
@jodh-intel , I updated this test with some changes please take a look :)

File: integration/oci_calls/oci_call_test.sh [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+
+	# Check arguments vs oci calls
+	for i in "${oci_call[@]}"; do
+		echo "$list_arguments" | grep -w "$i" > /dev/null
+	done
+}
+
+# Find the order of the arguments is equal to the order of the oci call
+function order_arguments() {
+	local -a final_arguments=$(echo ${list_arguments//state/}|awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}'|sed 's/ *$//')
```
Comment (jodh-intel) [inline integration/oci_calls/oci_call_test.sh]: Hi @GabyCT - please can you format this awk script across multiple lines, add some more braces for clarity along with comments explaining how this is working as it's rather terse atm! ;)

**Comment by GabyCT** [comment]
@jodh-intel changes applied

**Comment by GabyCT** [comment]
@jodh-intel , one question regarding `runc`, I ran with `runc` and enable the `"debug" : true` at the `daemon.json` and in the `journalctl`, I can not see the arguments in `dockerd`. Is that expected?

**Comment by jodh-intel** [comment]
Thanks @GabyCT!

lgtm

File: integration/oci_calls/oci_call_test.sh [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+#
+# SPDX-License-Identifier: Apache-2.0
+#
+# This test will verify the arguments of
+# running or stopping a container matches
+# with the OCI calls
+
+set -e
+
+cidir=$(dirname "$0")
```
Comment (chavafg) [inline integration/oci_calls/oci_call_test.sh]: this script is not on the ci directory, so I would recommend to change the name of the variable

**Comment by jodh-intel** [comment]
Metrics CI is failing:

```
22:42:36 time="2018-12-05T22:42:36Z" level=warning msg="Failed Maxval (3.045000 < 3.116000) for [boot-times]"
22:42:36 time="2018-12-05T22:42:36Z" level=warning msg="Check for [boot-times] failed [Failed]"
22:42:36 time="2018-12-05T22:42:36Z" level=warning msg=" with [[*F* boot-times 95.0% 107.4% 105.0% 10.0% 105.8% 112.1% 6.0% 1.4% 20]]"
22:42:36 time="2018-12-05T22:42:36Z" level=warning msg="Overall we failed"
22:42:36 
22:42:36 Report Summary:
22:42:36 +-----+----------------------+-------+--------+--------+-------+--------+--------+------+------+-----+
22:42:36 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   | RNG  | COV  | ITS |
22:42:36 +-----+----------------------+-------+--------+--------+-------+--------+--------+------+------+-----+
22:42:36 | *F* | boot-times           | 95.0% | 107.4% | 105.0% | 10.0% | 105.8% | 112.1% | 6.0% | 1.4% |  20 |
22:42:36 | P   | memory-footprint     | 85.0% | 85.2%  | 115.0% | 30.0% | 85.2%  | 85.2%  | 0.0% | 0.0% |   1 |
22:42:36 | P   | memory-footprint-ksm | 95.0% | 100.8% | 105.0% | 10.0% | 100.8% | 100.8% | 0.0% | 0.0% |   1 |
22:42:36 +-----+----------------------+-------+--------+--------+-------+--------+--------+------+------+-----+
22:42:36 Fails: 1, Passes 2
22:42:36 Failed
```

Hi @grahamwhaley - what's your view on these failures? Should we hold off merging the affected PRs until you get a chance to investigate?

**Comment by grahamwhaley** [comment]
/me thought I elaborated and laid out the plans last night on numerous channels....
Looks like all the metrics runs are failing similarly (boot time too high, and non-KSM footprint lower than expected). I am in the process of checking back through the history to see if there were specific PRs merged that effected those (and also if they are therefore valid or not). I'll send an email to the mailing list so everbody is on the same page, and then will update when we know what the state is.

**Comment by jodh-intel** [comment]
@grahamwhaley - sure. What I'm getting at is should we wait to merge, or just carry on? If it's a machine issue, I guess we should just press on and merge. But if it's a code issue, given we appear to have failed to spot the PR that caused this issue at the time, again, maybe we can just continue merging as you have the historical data to work out what broke us?

**Comment by grahamwhaley** [comment]
Probably merge. It feels like a PR merge issue. At least the fails are pretty consistent. So, merge if you think the PR should not have any performance impact. If you think a PR may have an impact, right now best get the submitter to use the [report generator](https://github.com/kata-containers/tests/tree/master/metrics/report) to do a local check to confirm.

**Comment by jodh-intel** [comment]
... did someone say merge... ? :smile:
