### PR TITLE
metrics: Fix unknown runtime error at memory test

### LINKED ISSUE #3935: metrics: Fix unknown runtime error at memory test

### PR DESCRIPTION
**Pull request by GabyCT**
Currently for the memory test we are using containerd and a as runtime io.containerd.kata.v2,
however, we can not extract general information like hypervisor path in order to get the pss
memory for the hypervisor. This PR fixes that issue by using kata-runtime when we are using
io.containerd.kata.v2 so we can get the information properly.

Fixes #3935

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: metrics/density/memory_usage.sh [hunk 1]
```diff
@@ -273,6 +273,16 @@ get_docker_memory_usage(){
 		sleep "$WAIT_TIME"
 	fi
 
+	if [ "$CTR_RUNTIME" == "io.containerd.kata.v2" ]; then
+		RUNTIME="kata-runtime"
+	elif [ "$CTR_RUNTIME" == "io.containerd.runc.v2" ]; then
+		RUNTIME="runc"
+	else
+		die "Unknown runtime"
```
Comment (wainersm) [inline metrics/density/memory_usage.sh:281]: Nit: print the CTR_RUNTIME value (e.g. "Unknown ctr runtime: $CTR_RUNTIME")

**Review by wainersm — APPROVED** [review]

**Review by devimc — APPROVED** [review]
thanks @GabyCT
