### PR TITLE
ci: Fail if OBS packages are not found on kata manager

### LINKED ISSUE #1691: kata-manager.sh fails with gpg: no valid OpenPGP data found
# Description of problem

1. Install ubuntu 19.04 server
1. sudo apt update
1. sudo apt upgrade
1. sudo reboot
1. bash -c "$(curl -fsSL https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh) install-docker-system"
[
# Expected result

Script completes without error.

# Actual result

Cloning into '/root/go/src/github.com/kata-containers/documentation'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 1487 (delta 1), reused 7 (delta 0), pack-reused 1471
Receiving objects: 100% (1487/1487), 1.83 MiB | 1.86 MiB/s, done.
Resolving deltas: 100% (867/867), done.
Cloning into '/root/go/src/github.com/kata-containers/tests'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 10169 (delta 0), reused 0 (delta 0), pack-reused 10165
Receiving objects: 100% (10169/10169), 6.67 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (5930/5930), done.
gpg: no valid OpenPGP data found.

### PR DESCRIPTION
**Pull request by GabyCT**
Fail in case that OBS packages are not found for a specific VERSION ID
while executing the installation guide from the documentation.

Fixes #1691

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: cmd/kata-manager/kata-manager.sh [hunk 1]
```diff
@@ -304,6 +304,14 @@ exec_document()
 
 	info "$msg"
 
+	# verify that we have OBS packages for the distro VERSION_ID
+	check_version=$(cat "${install_script}" | grep "${VERSION_ID}" || true)
```
Comment (jodh-intel) [inline cmd/kata-manager/kata-manager.sh]: Nit: Again, you don't need this `cat`. You might want to anchor the match for a more reliable result too:

```sh
check_version=$(grep -E "\<${VERSION_ID}\>" "${install_script}" || true)
```

Comment (GabyCT) [reply cmd/kata-manager/kata-manager.sh]: @jodh-intel thanks , done :)
