### PR TITLE
metrics: Webtooling script fixes

### LINKED ISSUE #3731: webtooling script fixes

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds some fixes like indentation and definition of the
variables.

Fixes #3731

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @GabyCT

**Comment by fidencio** [comment]
Sorry, I had to close and re-open so the static-checks would be triggered.

File: metrics/storage/webtooling.sh [hunk 1]
```diff
@@ -100,26 +100,24 @@ function main() {
...
+	done
 
-	# Verify that webtooling benchmark finished
 	CONTAINERS_ID=($(sudo ctr c list -q))
-	for i in $(seq 1 "$timeout"); do
- 		FILE_CMD="cat $file_path/$file_name | grep Geometric"
- 		check_file_content=$(sudo ctr t exec --exec-id "$(random_name)" "$i" sh -c "$FILE_CMD")
+	for j in $(seq 1 "$timeout"); do
+		FILE_CMD="cat $file_path/$file_name | grep Geometric"
+		check_file_content=$(sudo ctr t exec --exec-id "$(random_name)" "$i" sh -c "$FILE_CMD")
```
Comment (fidencio) [inline metrics/storage/webtooling.sh:116]:
```suggestion
		check_file_content=$(sudo ctr t exec --exec-id "$(random_name)" "$j" sh -c "$FILE_CMD")
```
The suggestion is, as you changed to for to use j instead of i, you need to adapt that inside the loop.

**Review by fidencio — CHANGES_REQUESTED** [review]
@GabyCT, please, take a look at the suggestion made.

File: metrics/storage/webtooling.sh (hunk 1 above)
Comment (GabyCT) [reply metrics/storage/webtooling.sh:116]: @fidencio if I use `j` instead of `i` it will take the variable of 1 to 180 which is something that I do not want, I am using i as it is the variable that is being used for the container id which is something that I need to use for the exec

Comment (fidencio) [reply metrics/storage/webtooling.sh:116]: Oh, now I see what you're doing.  It's confusing for the reader, I must admit, mainly because you're not looping here using $i, but rather using the last container you exec'ed.

May I bother you to add a comment about that?  I'm pretty sure the next time I'm sleepy and look at the code I'll have the same questions.

And thanks for the explanation, @GabyCT.

Comment (GabyCT) [reply metrics/storage/webtooling.sh:116]: @fidencio your welcome and thanks for the feedback

Comment (GabyCT) [reply metrics/storage/webtooling.sh:117]: @fidencio changes applied

File: metrics/storage/webtooling.sh [hunk 2]
```diff
@@ -100,26 +100,25 @@ function main() {
...
+	done
 
-	# Verify that webtooling benchmark finished
 	CONTAINERS_ID=($(sudo ctr c list -q))
-	for i in $(seq 1 "$timeout"); do
- 		FILE_CMD="cat $file_path/$file_name | grep Geometric"
- 		check_file_content=$(sudo ctr t exec --exec-id "$(random_name)" "$i" sh -c "$FILE_CMD")
+	for j in $(seq 1 "$timeout"); do
+		FILE_CMD="cat $file_path/$file_name | grep Geometric"
+		# Here we are using i to iterate with the proper container id and perform an exec
```
Comment (GabyCT) [inline metrics/storage/webtooling.sh:116]: ^ Here it is the comment @fidencio

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Comment by fidencio** [comment]
Wow, static checks for 1.14, that's something I thought we had removed.

**Comment by fidencio** [comment]
> Wow, static checks for 1.14, that's something I thought we had removed.

Ah, I removed those from the kata-containers repo.  For this one I've opened https://github.com/kata-containers/tests/pull/3734
