### PR TITLE
ci: Fix docker installation for rhel 8

### LINKED ISSUE #2892: Fix docker installation for rhel 8

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the possiblity to install docker 18.06 by using
the CentOS 7 repository as the latest CentOS repository has docker
19.

Fixes #2892

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@jodh-intel any idea of why the check porting label is failing?

**Review by cmaf — APPROVED** [review]

**Comment by jodh-intel** [comment]
@GabyCT - Yes; the `backport` label is only used for a PR that itself *is* a backport. So:

- If this is the "original" PR, change the `backport` label to `needs-backport`.
- If this PR is an actual backport PR (that is to say, there is another PR which this is based on), remove the `no-forward-port-needed` label.

See the table of valid porting label combinations here: https://github.com/kata-containers/kata-containers/issues/634#issuecomment-688439361.

More details here: https://github.com/kata-containers/community/pull/178

File: cmd/container-manager/manage_ctr_mgr.sh [hunk 1]
```diff
@@ -136,7 +136,7 @@ install_docker(){
 			repo_url="https://download.docker.com/linux/centos/docker-ce.repo"
 			sudo yum-config-manager --add-repo "$repo_url"
 			# With this we will be able to install docker 18.06
-			if [ "$ID" == "centos" ] && [ "$VERSION_ID" -ge "8" ]; then
+			if [ "$ID" == "centos" ] && [ "$VERSION_ID" -ge "8" ] || [ "$ID" == "rhel" ] && [ "$VERSION_ID" -ge "8" ]; then
```
Comment (fidencio) [inline cmd/container-manager/manage_ctr_mgr.sh:139]: @GabyCT, this check is too complicated for my simple mind.
I'd suggest we do:
- Remoe the check for the "$ID", as at this point it can only be "centos" or "rhel"
- Check only for the "$VERSION_ID", as we'd do the change for both "centos" or "rhel", if those are >= 8

So, in the end the check would be:
```
if [ "$VERSION_ID" -ge "8" ]; then
  ...
fi
```

Comment (jodh-intel) [reply cmd/container-manager/manage_ctr_mgr.sh:139]: I agree this should be simplified but is `VERSION_ID` guaranteed to be an integer for any release of CentOS/RHEL? The spec says it could be a floating point or contain alphabetics:

- https://www.freedesktop.org/software/systemd/man/os-release.html

Comment (fidencio) [reply cmd/container-manager/manage_ctr_mgr.sh:139]: @jodh-intel, you're right about your point, but I sincerely think we can simplify it even more, as we can simply do the `sed -i ...` regardless of the version.

Do we test if RHEL / CentOS 7? I don't think so. But if we do, changing $releasever to 7 would just match;
For 8, we want to do that for both CenOS and RHEL.

**Comment by fidencio** [comment]
@GabyCT, why do we need to use docker 18.06 version instead of using the latest available for EL8?
I saw issues like:
```
12:36:11 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
12:36:11 /tmp/go-link-925019689/000008.o: In function `pluginOpen':
12:36:11 /workdir/go/src/plugin/plugin_dlopen.go:19: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 /usr/bin/ld: cannot find -lseccomp
12:36:11 /tmp/go-link-925019689/000023.o: In function `mygetgrouplist':
12:36:11 /workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetgrgid_r':
12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetgrnam_r':
12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetpwnam_r':
12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetpwuid_r':
12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 /tmp/go-link-925019689/000004.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
12:36:11 /tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
12:36:11 collect2: error: ld returned 1 exit status
12:36:11 
12:36:11 make[1]: *** [Makefile:77: _output/containerd] Error 2
12:36:11 make[1]: Leaving directory '/tmp/jenkins/workspace/kata-containers-tests-rhel-8-q35-PR/go/src/github.com/containerd/cri'
```

I start to think that if we want to stick to a speciic docker version, we better build it.

**Comment by fidencio** [comment]
Here's a run using latest docker version: http://jenkins.katacontainers.io/job/kata-containers-tests-rhel-8-q35-PR/103/

**Comment by fidencio** [comment]
> @GabyCT, why do we need to use docker 18.06 version instead of using the latest available for EL8?
> I saw issues like:
> 
> ```
> 12:36:11 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
> 12:36:11 /tmp/go-link-925019689/000008.o: In function `pluginOpen':
> 12:36:11 /workdir/go/src/plugin/plugin_dlopen.go:19: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 /usr/bin/ld: cannot find -lseccomp
> 12:36:11 /tmp/go-link-925019689/000023.o: In function `mygetgrouplist':
> 12:36:11 /workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetgrgid_r':
> 12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetgrnam_r':
> 12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetpwnam_r':
> 12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 /tmp/go-link-925019689/000022.o: In function `mygetpwuid_r':
> 12:36:11 /workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 /tmp/go-link-925019689/000004.o: In function `_cgo_26061493d47f_C2func_getaddrinfo':
> 12:36:11 /tmp/go-build/cgo-gcc-prolog:58: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
> 12:36:11 collect2: error: ld returned 1 exit status
> 12:36:11 
> 12:36:11 make[1]: *** [Makefile:77: _output/containerd] Error 2
> 12:36:11 make[1]: Leaving directory '/tmp/jenkins/workspace/kata-containers-tests-rhel-8-q35-PR/go/src/github.com/containerd/cri'
> ```
> 
> I start to think that if we want to stick to a speciic docker version, we better build it.

Okay, this is not exactly trivial to follow.

Looking at the logs again it seems to be happening when building containerd. But why do we build containerd if we're already installing it from docker-ce?

I'd appreciated a quick overview of the process, as I have the feeling it's so complex that we may have been losing ourselves in the middle of it.

File: cmd/container-manager/manage_ctr_mgr.sh (hunk 1 above)
Comment (GabyCT) [reply cmd/container-manager/manage_ctr_mgr.sh:139]: @fidencio, in the past we tested RHEL 7 and CentOS 7.

**Comment by GabyCT** [comment]
@fidencio the supported version of docker is https://github.com/kata-containers/runtime/blob/master/versions.yaml#L215, we can't use 19 because it does not support devicemapper.

File: cmd/container-manager/manage_ctr_mgr.sh (hunk 1 above)
Comment (fidencio) [reply cmd/container-manager/manage_ctr_mgr.sh:139]: Okay, so, please, just remove the conditions and do the sed unconditionally.

**Review by fidencio — APPROVED** [review]
lgtm!
