### PR TITLE
integration/pmem: fix bare metal CI

### LINKED ISSUE #3837: pmem CI failing due docker limit
The docker limit issue hit PMEM CI with
```
22:07:38 Creating rootfs for ubuntu
22:07:38 /home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/rootfs.sh -o 2.2.0-alpha1-e155fb2b199c6ff60eed028e6c04dbe47d544823 -r /home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/ubuntu_rootfs ubuntu
22:07:38 INFO: rootfs_lib.sh file found. Loading content
22:07:38 INFO: Detecting agent rust version
22:07:38 INFO: Get rust version from /home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/../../../versions.yaml
22:07:39 Required rust version: 1.47.0
22:07:39 INFO: Detecting musl version
22:07:39 INFO: Get musl version from /home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/../../../versions.yaml
22:07:39 Required musl version: 1.1.23
22:07:39 ~/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/rootfs-builder/ubuntu ~/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder
22:07:39 ~/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder
22:07:39 Sending build context to Docker daemon  10.75kB

22:07:39 Step 1/6 : ARG IMAGE_REGISTRY=docker.io
22:07:39 Step 2/6 : FROM ${IMAGE_REGISTRY}/ubuntu:20.04
22:07:40 20.04: Pulling from library/ubuntu
22:07:40 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
22:07:40 Makefile:93: recipe for target '/home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done' failed
22:07:40 make: *** [/home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done] Error 1
22:07:40 [install_kata_image.sh:50] ERROR: sudo -E USE_DOCKER=1 DISTRO=ubuntu make -e image
22:07:40 [install_kata.sh:22] ERROR: .ci/install_kata_image.sh 
22:07:40 Build step 'Execute shell' marked build as failure
```
/cc @devimc

### PR DESCRIPTION
**Pull request by devimc**
* Specify a version for the registry image
* Don't re-run a registry from the pmem test
* Don't delete all docker images to avoid rate limit issue

fixes #3837

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
@devimc any idea why https://github.com/kata-containers/tests/blob/54534e0ef360b1216df842d8398d2fff1cc0c905/integration/kubernetes/cleanup_env.sh#L43 did not remove the container so it would have to be started again by the pmem tests?

**Comment by devimc** [comment]
@Jakob-Naucke pmem test uses kubernetes scripts (init and cleanup)

>  sudo -E "${container_engine}" rm -f "${registry_name}" || true 

this is a bug that is being hidden by `|| true`, right? I think you forgot the **image** subcommand:

`sudo -E "${container_engine}" **image** rm -f "${registry_name}" || true `

do you want me to include the fix in this PR?

File: integration/pmem/pmem_test.sh [hunk 1]
```diff
@@ -40,7 +40,6 @@ fi
 
 init() {
 	${dir_path}/../../integration/kubernetes/init.sh
-	docker run -d -p 5000:5000 --restart=always --name registry registry:2
```
Comment (Jakob-Naucke) [inline integration/pmem/pmem_test.sh:43]: @devimc no, I did intend to use `docker rm`, not `docker image rm`. It's just that from the line reference here, I take there is no need to run the registry any more, which confuses me because the container should have been removed.

**Review by GabyCT — APPROVED** [review]

File: integration/pmem/pmem_test.sh (hunk 1 above)
Comment (Jakob-Naucke) [reply integration/pmem/pmem_test.sh:43]: @devimc I don't feel this is resolved. Did you have issues when the line referenced here was present? Also, on the VFIO CI, the registry container wouldn't even have been launched because we don't run the k8s tests there.

**Comment by dborquez** [comment]
LGTM

**Review by dborquez — APPROVED** [review]
LGTM

File: integration/pmem/pmem_test.sh (hunk 1 above)
Comment (Jakob-Naucke) [reply integration/pmem/pmem_test.sh:43]: wait, are we running the pmem tests on any CI in the first place?

Comment (GabyCT) [reply integration/pmem/pmem_test.sh:43]: @Jakob-Naucke yes we are running pmem tests on a CI and we test this PR locally and is fixing the pmem CI

Comment (devimc) [reply integration/pmem/pmem_test.sh:43]: > Did you have issues when the line referenced here was present? 

yes, because that port was already in use

> Also, on the VFIO CI, the registry container wouldn't even have been launched because we don't run the k8s tests there.

does VFIO CI need a registry?  I don't think so

Comment (Jakob-Naucke) [reply integration/pmem/pmem_test.sh:43]: I thought the VFIO CI ran the pmem tests, but it doesn't seem so. Let me TAL...

Comment (Jakob-Naucke) [reply integration/pmem/pmem_test.sh:43]: Ah. It's because the pmem tests also run our k8s init. Let me resolve this conversation. Sorry for the noise! But I wanted to make sure I'd understand the change.

**Review by Jakob-Naucke — APPROVED** [review]
LGTM!

**Comment by devimc** [comment]
thanks @Jakob-Naucke
