### PR TITLE
tests: Skip kubernetes and openshift tests for initrd.

### LINKED ISSUE #380: Skip kubernetes and openshift tests for initrd
As currently Kubernetes and Openshift tests are not working with INITRD (https://github.com/kata-containers/tests/issues/335), we need to skip them in order to enable a Jenkins job (https://github.com/kata-containers/tests/issues/190).

### PR DESCRIPTION
**Pull request by GabyCT**
As currently Kubernetes and Openshift tests are not working
with INITRD, we need to skip them in order to enable
a Jenkins job.

Fixes #380

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: integration/kubernetes/run_kubernetes_tests.sh [hunk 1]
```diff
@@ -18,6 +18,13 @@ if [ "$ID" != ubuntu  ]; then
 	exit
 fi
 
+# Currently, Kubernetes tests are not working with initrd.
+if [ "$TEST_INITRD" = yes ] && [ "$AGENT_INIT" = yes ] && [ "$OSBUILDER_DISTRO" = alpine ]; then
```
Comment (jodh-intel) [inline integration/kubernetes/run_kubernetes_tests.sh]: - Where is `OSBUILDER_DISTRO` set?
- Yep, I had to be careful with initrd's for https://github.com/kata-containers/osbuilder/pull/102, see:
  https://github.com/kata-containers/osbuilder/blob/master/tests/image_creation.bats#L281. But could this test just use the first to tests?:
  ```
  if [ "$TEST_INITRD" = yes ] && [ "$AGENT_INIT" = yes ]; then
  ```

**Comment by GabyCT** [comment]
@jodh-intel changes applied

**Comment by jodh-intel** [comment]
lgtm

**Comment by caoruidong** [comment]
LGTM
