### PR TITLE
tests/cri-containerd: Skip TestContainerListStatsWithSandboxIdFilter with QEMU

### LINKED ISSUE #2329: clh: cri-containerd: TestContainerListStatsWithSandboxIdFilter  fails
# Description of problem

Running CI with `cloud-hypervisor` fails with cri-containerd test `TestContainerListStatsWithSandboxIdFilter  `

# Actual result

```
     require.go:858: 
16:16:56         	Error Trace:	container_stats_test.go:341
16:16:56         	            				container_stats_test.go:241
16:16:56         	Error:      	Should NOT be empty, but was 0
16:16:56         	Test:       	TestContainerListStatsWithSandboxIdFilter
16:16:56 FAIL
16:16:56 ./hack/test-utils.sh: line 82: 54670 Terminated              keepalive "sudo PATH=${PATH} ${ROOT}/_output/${CONTAINERD_BIN} ${CONTAINERD_FLAGS}" ${RESTART_WAIT_PERIOD} &> ${report_dir}/containerd.log
```

### PR DESCRIPTION
**Pull request by wainersm**
On commit fa5b6af50e8382f TestContainerListStatsWithSandboxIdFilter
is skipped from cri-containerd test suite for the Cloud Hypervisor.

This test is also failing with QEMU, so skip it as well.

Fixes #2329

Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
@wainersm, the test was not skipped:
```
17:58:37 === RUN   TestContainerListStatsWithSandboxIdFilter
17:58:37     TestContainerListStatsWithSandboxIdFilter: container_stats_test.go:192: Create a pod config and run sandbox container
17:58:40     TestContainerListStatsWithSandboxIdFilter: container_stats_test.go:200: Create a container config and run containers in a pod
17:58:43     TestContainerListStatsWithSandboxIdFilter: container_stats_test.go:222: Fetch container stats for each container with Filter
17:58:44     TestContainerListStatsWithSandboxIdFilter: container_stats_test.go:239: Verify container stats for sandbox "d998c4c8c8c23c3948da57fd22296819d34cab8d58fda5ef72dadaf7462502c1"
17:58:44     TestContainerListStatsWithSandboxIdFilter: container_stats_test.go:341: 
17:58:44         	Error Trace:	container_stats_test.go:341
17:58:44         	            				container_stats_test.go:241
17:58:44         	Error:      	Should NOT be empty, but was 0
17:58:44         	Test:       	TestContainerListStatsWithSandboxIdFilter
17:58:45 --- FAIL: TestContainerListStatsWithSandboxIdFilter (8.25s)
17:58:45 FAIL
```

File: integration/containerd/cri/integration-tests.sh [hunk 1]
```diff
@@ -18,6 +18,7 @@ RUNTIME=${RUNTIME:-containerd-shim-kata-v2}
 SHIMV2_TEST=${SHIMV2_TEST:-""}
 FACTORY_TEST=${FACTORY_TEST:-""}
 KILL_VMM_TEST=${KILL_VMM_TEST:-""}
+KATA_HYPERVISOR="${KATA_HYPERVISOR:-qemu}"
```
Comment (fidencio) [inline integration/containerd/cri/integration-tests.sh:21]: Hmm. I wonder whether not setting the KATA_HYPERVISOR was proposital or a bug that wasn't caught during coding / reviewing.
@GabyCT, @jcvenegas, do you know?

Comment (wainersm) [reply integration/containerd/cri/integration-tests.sh:21]: On commit fa5b6af it was introduced the conditional to skip the test in case of KATA_HYPERVISOR is clh. The CI jobs which test clh will set KATA_HYPERVISOR so it works. But for default jobs, i.e. to test with qemu, that variable might not be set on env (some scripts assume the default is "qemu"). Thus, I believe it is a bug. Anyway, Gaby and Carlos will know for sure.

**Review by fidencio — APPROVED** [review]
lgtm!

**Comment by fidencio** [comment]
We still have to increase the sonobuoy timeout in order to ensure the -k8s-e2e-minimal CIs pass.

**Comment by GabyCT** [comment]
I think we can merge this as it solves the other CI issues and it is not related with the e2e failures.

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
> I think we can merge this as it solves the other CI issues and it is not related with the e2e failures.

Ack, I am going to force merge this one.

**Comment by amshinde** [comment]
@wainersm Can you resolve the travis failure?
```
ERROR: Commit 48c7f946ef40924a46d77c81c453e0ae72e55afd: subject too long (max 75, got 78): "tests/cri-containerd: Skip TestContainerListStatsWithSandboxIdFilter with QEMU"
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 1.
```

**Comment by wainersm** [comment]
@amshinde updated the PR, the Travis issue should be fixed.

**Comment by fidencio** [comment]
@jcvenegas, @likebreath,
```
02:55:23 ok 1 Copy file in a pod
02:55:25 not ok 2 Copy from pod to host
```

Shall we consider not making the clh-k8s-containers job required?

**Comment by wainersm** [comment]
> @jcvenegas, @likebreath,
> 
> ```
> 02:55:23 ok 1 Copy file in a pod
> 02:55:25 not ok 2 Copy from pod to host
> ```
> 
> Shall we consider not making the clh-k8s-containers job required?
> 

I'm in favour of doing that, then we could merge this PR which will make the ubuntu jobs to pass again.

Yesterday I glanced at this "Copy from pod to host". The test is very simple so I couldn't find any flaw on its implementation. Maybe it is flagging kata bug?

**Review by jcvenegas — APPROVED** [review]
