### PR TITLE
ci: Fix that the docker installation sometimes fails in opensuse

### LINKED ISSUE #1326: opensuse: docker installation fails sometimes
Have seen this a couple of times:
```
11:08:54 Problem: conflicting requests
11:08:54  Solution 1: Following actions will be done:
11:08:54   do not ask to delete all solvables providing docker.x86_64 = 18.06.1_ce-lp150.5.6.1
11:08:54   keep docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-lp150.3.3.1.x86_64
11:08:54   keep docker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-lp150.5.7.1.x86_64
11:08:54  Solution 2: remove lock to allow removal of docker-18.06.1_ce-lp150.5.6.1.x86_64
11:08:54 
11:08:54 Choose from above solutions by number or cancel [1/2/c] (c): c
11:08:54 Build step 'Execute shell' marked build as failure
```

### PR DESCRIPTION
**Pull request by GabyCT**
This will fix that sometimes the docker installation fails in opensuse.
This restarts docker so we can retrieve properly docker information.

Fixes #1326

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: cmd/container-manager/manage_ctr_mgr.sh [hunk 1]
```diff
@@ -210,14 +217,20 @@ get_docker_default_runtime(){
...
 }
 
 get_docker_package_name(){
 	if [ "$ID" == "ubuntu" ] || [ "$ID" == "debian" ]; then
 		dpkg --get-selections | awk '/docker/ {print $1}'
-	elif [ "$ID" == "fedora" ] || [ "$ID" == "centos" ] || [[ "$ID" =~ ^opensuse.*$ ]] || [ "$ID" == "sles" ]; then
+	elif [ "$ID" == "fedora" ] || [ "$ID" == "centos" ] || [ "$ID" == "sles" ]; then
 		rpm -qa | grep docker | grep -v selinux
+	elif [[ "$ID" =~ ^opensuse.*$ ]]; then
+		rpm -qa | grep docker-$(get_docker_version) | grep -v selinux
```
Comment (chavafg) [inline cmd/container-manager/manage_ctr_mgr.sh]: I see that docker has other dependencies that are not removed when uninstalling it, but we should also uninstall them as they may conflict with a newer/older version of docker, e.g.: 
```
fuentess@test-opensuse:~> sudo zypper install 'docker<18.09'
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: docker-18.06.1_ce-lp150.5.6.1.x86_64 requires docker-libnetwork-git = 3ac297bc7fd0afec9051bbb47024c9bc1d75bf5b, but this requirement cannot be provided
  not installable providers: docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-lp150.3.3.1.x86_64[openSUSE-Leap-15.0-Update]
 Solution 1: Following actions will be done:
  downgrade of docker-libnetwork-0.7.0.1+gitr2711_2cfbf9b1f981-lp150.3.10.1.x86_64 to docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-lp150.3.3.1.x86_64
  downgrade of containerd-1.2.2-lp150.4.10.1.x86_64 to containerd-1.1.2-lp150.4.6.1.x86_64
  downgrade of docker-runc-1.0.0rc6+gitr3748_96ec2177ae84-lp150.5.14.1.x86_64 to docker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-lp150.5.7.1.x86_64
 Solution 2: do not install docker-18.06.1_ce-lp150.5.6.1.x86_64
 Solution 3: break docker-18.06.1_ce-lp150.5.6.1.x86_64 by ignoring some of its dependencies

```

File: cmd/container-manager/manage_ctr_mgr.sh [hunk 2]
```diff
@@ -188,6 +188,13 @@ remove_docker(){
 	if [ -z "$pkg_name" ]; then
 		die "Docker not found in this system"
 	else
+		# Check docker version at versions.yaml from the runtime
+		docker_version=$(get_version "externals.docker.version" | cut -d '-' -f1 | cut -d 'v' -f2)
+		# Do not remove docker if the version is equal to the one
+		# that is supported
+		install_docker_version=$(get_docker_version)
+		[ "$docker_version" == "$install_docker_version" ] && return
```
Comment (chavafg) [inline cmd/container-manager/manage_ctr_mgr.sh]: This shouldn't be part of the remove_docker as it may be the case that a user just want to remove the package even if it is the version that we support. I'll prefer to add this check inside the `install_docker()` 
Btw, this is also being checked on https://github.com/kata-containers/tests/blob/master/.ci/setup.sh#L51-L59

File: cmd/container-manager/manage_ctr_mgr.sh [hunk 3]
```diff
@@ -210,14 +217,20 @@ get_docker_default_runtime(){
 }
 
 get_docker_version(){
-	sudo docker version | awk '/Engine/{getline; print $2 }'
+	if [[ "$ID" =~ ^opensuse.*$ ]]; then
+		sudo docker version --format '{{.Client.Version}}' | cut -d '.' -f1-2
```
Comment (chavafg) [inline cmd/container-manager/manage_ctr_mgr.sh]: I think you are only seeing client version because the docker service is stopped. I think we can use the client version for all distros to don't rely on docker service being up.

**Comment by GabyCT** [comment]
@chavafg changes applied
