### PR TITLE
tests: Add docker-compose tests.

### LINKED ISSUE #108: docker: add docker compose tests
We have an open issue against clear containers regarding failed host resolution during a basic network test between containers.  Once resolved, we'll want to exercise this in our integration testing.  

In general we should also be testing docker compose.

### PR DESCRIPTION
**Pull request by GabyCT**
Test docker-compose functionality by running a REDIS application.

Fixes #108

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

File: integration/docker-compose/docker-compose.sh [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+# Docker compose version
+VERSION="1.20.0"
+# URL
+URL="http://localhost:5000"
+# Image name
+IMAGE_NAME="dockercompose_web"
+# Installation path
+INSTALLATION_PATH="/usr/local/bin/docker-compose"
+
+Skip("Issue: https://github.com/clearcontainers/runtime/issues/1042")
```
Comment (devimc) [inline integration/docker-compose/docker-compose.sh]: I wonder if this file should be .bats

**Comment by GabyCT** [comment]
@devimc changes applied

**Comment by devimc** [comment]
I wonder a new target should be added to Makefile, `docker-compose` might be...

**Comment by devimc** [comment]
lgtm

**Comment by GabyCT** [comment]
@chavafg could you please take a look. thanks

File: integration/docker-compose/docker-compose.bats [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+	if [ $? -ne 0 ]; then
+		echo >&2 "ERROR: Docker compose should be installed in the system."
+		# Install docker-compose
+		echo >&2 "Installing Docker compose."
+		curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-`uname -s`-`uname -m` -o ${INSTALLATION_PATH}
+		sudo -E chmod +x ${INSTALLATION_PATH}
+	fi
+
+	# Run the services in the background
+	docker-compose up -d
```
Comment (chavafg) [inline integration/docker-compose/docker-compose.bats]: this line won't be executed if the condition on L19 is met and the test would fail if this is not run.

File: integration/docker-compose/docker-compose.bats [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+}
+
+@test "run REDIS application" {
+	skip "This is not working (https://github.com/kata-containers/tests/issues/108)"
```
Comment (chavafg) [inline integration/docker-compose/docker-compose.bats]: I think the issue here is: https://github.com/clearcontainers/runtime/issues/1042

File: integration/docker-compose/docker-compose.bats (hunk 2 above)
Comment (GabyCT) [reply integration/docker-compose/docker-compose.bats]: @chavafg changes applied thanks

**Comment by chavafg** [comment]
lgtm
